version: '3.2'
networks:
  mongo-network:
    external: true

services:
  blueofflinesink:
      image: ${REGISTRY}/hptiger/blueofflinesink:${TAG}
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      ports:
        - 8100:8080
      environment:
        - SPRING_PROFILES_ACTIVE=prod
      networks:       
        - mongo-network